Repository CozyWool/Quizzify, pull requests merged in 2024-03, with the labels that each got.

#8 Настройка локализации приложения
  Quizzify/Quizzify/App.xaml.cs
  Quizzify/Quizzify/MainWindow.xaml.cs
  Quizzify/Quizzify/Quizzify.csproj
  Quizzify/Quizzify/Settings/Language/LanguageSettings.cs
  Quizzify/Quizzify/Settings/Language/MainSettings.cs
Labels: Localization

#14 feature-1_and_feature-2
  Quizzify/Quizzify/Resources/Locales/Resources.Designer.cs
  Quizzify/Quizzify/Resources/Locales/Resources.resx
  Quizzify/Quizzify/Resources/Locales/Resources.ru-RU.resx
  Quizzify/Quizzify/View/AuthorizationWindow.xaml
  Quizzify/Quizzify/View/AuthorizationWindow.xaml.cs
  Quizzify/Quizzify/View/RegistrationWindow.xaml
  Quizzify/Quizzify/View/RegistrationWindow.xaml.cs
Labels: UI

#15 Feature 18
  Quizzify/Quizzify/Model/Package/PackageModel.cs
  Quizzify/Quizzify/Model/Package/QuestionModel.cs
  Quizzify/Quizzify/Model/Package/RoundModel.cs
  Quizzify/Quizzify/Model/Users/PlayerModel.cs
  Quizzify/Quizzify/Model/Users/RegistrationModel.cs
  Quizzify/Quizzify/Model/Users/SignInModel.cs
Labels: enhancement

#19 feature-17 (Добавил базовую команду и Generic версию)
  Quizzify/Quizzify.Client/Command/Command.cs
  Quizzify/Quizzify.Client/Command/GenericCommand.cs
Labels: enhancement

#18 Регистрация пользователя
  Quizzify/Quizzify.Client/App.xaml.cs
  Quizzify/Quizzify.Client/Mappers/MappingUser.cs
  Quizzify/Quizzify.Client/Model/Users/RegistrationModel.cs
  Quizzify/Quizzify.Client/Quizzify.Client.csproj
  Quizzify/Quizzify.Client/View/RegistrationView.xaml
  Quizzify/Quizzify.Client/ViewModel/RegistrationViewModel.cs
  Quizzify/Quizzify.Client/appsettings.json
  Quizzify/Quizzify.DataAccess/Contexts/DbQuizzifyContext.cs
Labels: enhancement
